+define+DUTNAME=DATASETNAME_bnn_seq
+define+TBNAME=tbDATASETNAME_bnn_seq
+define+TESTCASES="DATASETNAME.csv.tbp"
+define+PARAMS="DATASETNAME.csv.par"
+define+HRDCD="weightsDATASETNAME.csv.h5.hrdcd"
+define+BSTRINGS="DATASETNAME.bstr"
+incdir+../../datasets/bnn1_40_nobnorm_models/bnnprints/
+incdir+../../trainingdata/tbparams/
+incdir+../../datasets/bnn1_40_nobnorm_models/bitstrings/
