+define+DUTNAME=DATASETNAME_bs
+define+TBNAME=tbDATASETNAME_bs
+define+TESTCASES="DATASETNAME.csv.tbp"
+define+PARAMS="DATASETNAME.csv.par"
+define+HRDCD="weightsDATASETNAME.csv.h5.hrdcd"
+define+BSTRINGS="DATASETNAME.bstr"
+incdir+../../models/bnn1_40_nobnorm_models/bnnprints/
+incdir+../../trainingdata/retbparams/
+incdir+../../models/bnn1_40_nobnorm_models/bitstrings/
